server:
  port: 9100

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
       # hikari:
         #   connection-test-query: SELECT 1
         #  maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ashuDb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#        driver-class-name: org.h2.Driver
#        jdbc-url: jdbc:h2:mem:testdb/auth
        username: root
        password: 
        initialization-mode: always
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect 